<?php
/**
 * Wally Grow Child Theme
 *
 * Bootstraps the child theme and prepares the site for future
 * customization of Home, Shop, Single Product, Cart and Gutenberg blocks.
 */

if (!defined('ABSPATH')) {
    exit;
}

$wally_grow_theme = wp_get_theme(get_stylesheet());
define(
    'WALLY_GROW_CHILD_VERSION',
    $wally_grow_theme->exists() ? (string) $wally_grow_theme->get('Version') : '1.2.8'
);

/**
 * WhatsApp number in international format, digits only.
 * Override in wp-config.php: define('WALLY_GROW_WHATSAPP_NUMBER', '54911...');
 * Optional full URL override: define('WALLY_GROW_WHATSAPP_URL', 'https://wa.me/...');
 */
if (!defined('WALLY_GROW_WHATSAPP_NUMBER')) {
    define('WALLY_GROW_WHATSAPP_NUMBER', '');
}

/**
 * Paste the real shortcode generated by GR Widget between the quotes.
 */
if (!defined('WALLY_GROW_REVIEWS_SHORTCODE')) {
    define('WALLY_GROW_REVIEWS_SHORTCODE', '[grwi_widget id="wp_QVivpY3g4HVauXFVTj7z"]');
}

/**
 * Optional public Google review URLs. Leave empty to hide the corresponding button.
 */
if (!defined('WALLY_GROW_GOOGLE_REVIEW_URL')) {
    define('WALLY_GROW_GOOGLE_REVIEW_URL', '');
}

if (!defined('WALLY_GROW_GOOGLE_REVIEWS_URL')) {
    define('WALLY_GROW_GOOGLE_REVIEWS_URL', '');
}

require_once get_stylesheet_directory() . '/inc/contact.php';

if (!function_exists('wally_grow_child_setup')) {
    function wally_grow_child_setup() {
        load_theme_textdomain('wally-grow-child', get_stylesheet_directory() . '/languages');

        add_theme_support('title-tag');
        add_theme_support('post-thumbnails');
        add_theme_support('custom-logo', array(
            'height' => 64,
            'width' => 240,
            'flex-height' => true,
            'flex-width' => true,
        ));
        add_theme_support('editor-styles');
        add_editor_style('assets/css/fonts.css');
        add_editor_style('assets/css/editor.css');

        add_theme_support('align-wide');
        add_theme_support('responsive-embeds');
        add_theme_support('wp-block-styles');
        add_theme_support('custom-spacing');
        add_theme_support('html5', array('search-form', 'comment-form', 'comment-list', 'gallery', 'caption', 'style', 'script'));

        register_nav_menus(array(
            'primary' => __('Primary Menu', 'wally-grow-child'),
        ));
    }
}
add_action('after_setup_theme', 'wally_grow_child_setup');

if (!function_exists('wally_grow_child_enqueue_assets')) {
    function wally_grow_child_enqueue_assets() {
        wp_enqueue_style(
            'wally-grow-fonts',
            get_stylesheet_directory_uri() . '/assets/css/fonts.css',
            array(),
            WALLY_GROW_CHILD_VERSION
        );

        wp_enqueue_style(
            'blocksy-parent-style',
            get_template_directory_uri() . '/style.css',
            array(),
            wp_get_theme('blocksy')->get('Version')
        );

        wp_enqueue_style(
            'wally-grow-child-style',
            get_stylesheet_uri(),
            array('blocksy-parent-style', 'wally-grow-fonts'),
            WALLY_GROW_CHILD_VERSION
        );

        wp_enqueue_style(
            'wally-grow-child-components',
            get_stylesheet_directory_uri() . '/assets/css/child.css',
            array('wally-grow-child-style', 'ct-main-styles'),
            WALLY_GROW_CHILD_VERSION
        );

        $child_js = get_stylesheet_directory() . '/assets/js/child.js';
        if (is_readable($child_js) && filesize($child_js) > 80) {
            wp_enqueue_script(
                'wally-grow-child-script',
                get_stylesheet_directory_uri() . '/assets/js/child.js',
                array(),
                WALLY_GROW_CHILD_VERSION,
                true
            );
        }
    }
}
add_action('wp_enqueue_scripts', 'wally_grow_child_enqueue_assets');

/**
 * Blocksy's Customizer may still request Open Sans. Brand fonts replace it,
 * so the unused Google request can be removed safely.
 */
add_action('wp_enqueue_scripts', function () {
    wp_dequeue_style('blocksy-fonts-font-source-google');
}, 100);

/**
 * Disable Blocksy Companion's trending-posts strip.
 *
 * The extension was rendering the default "Hello world!" post immediately
 * before the global footer. Pointing its output at an unused hook prevents
 * that entire section from being added to public pages.
 *
 * Safety net: Companion historically attaches at priority 50 on
 * blocksy:template:after. Re-test after Companion updates.
 */
add_filter('theme_mod_trending_block_location', function () {
    return 'wally_grow:disabled_trending_block';
});

add_action('wp', function () {
    remove_all_actions('blocksy:template:after', 50);
}, PHP_INT_MAX);

require_once get_stylesheet_directory() . '/inc/setup.php';
require_once get_stylesheet_directory() . '/inc/woocommerce.php';
require_once get_stylesheet_directory() . '/inc/footer.php';
