<?php
/**
 * Wally Grow Child Theme
 *
 * Bootstraps the child theme and prepares the site for future
 * customization of Home, Shop, Single Product, Cart and Gutenberg blocks.
 */

if (!defined('ABSPATH')) {
    exit;
}

define('WALLY_GROW_CHILD_VERSION', '1.2.7');

/**
 * WhatsApp number in international format, using digits only.
 * Example format: country code + area code + number.
 */
if (!defined('WALLY_GROW_WHATSAPP_NUMBER')) {
    define('WALLY_GROW_WHATSAPP_NUMBER', '');
}

/**
 * Paste the real shortcode generated by GR Widget between the quotes.
 */
if (!defined('WALLY_GROW_REVIEWS_SHORTCODE')) {
    define('WALLY_GROW_REVIEWS_SHORTCODE', '[grwi_widget id="wp_QVivpY3g4HVauXFVTj7z"]');
}

/**
 * Optional public Google review URLs. Leave empty to hide the corresponding button.
 */
if (!defined('WALLY_GROW_GOOGLE_REVIEW_URL')) {
    define('WALLY_GROW_GOOGLE_REVIEW_URL', '');
}

if (!defined('WALLY_GROW_GOOGLE_REVIEWS_URL')) {
    define('WALLY_GROW_GOOGLE_REVIEWS_URL', '');
}

if (!function_exists('wally_grow_child_setup')) {
    function wally_grow_child_setup() {
        load_theme_textdomain('wally-grow-child', get_stylesheet_directory() . '/languages');

        add_theme_support('title-tag');
        add_theme_support('post-thumbnails');
        add_theme_support('custom-logo', array(
            'height' => 64,
            'width' => 240,
            'flex-height' => true,
            'flex-width' => true,
        ));
        add_theme_support('editor-styles');
        add_editor_style('assets/css/editor.css');

        add_theme_support('align-wide');
        add_theme_support('responsive-embeds');
        add_theme_support('wp-block-styles');
        add_theme_support('custom-spacing');
        add_theme_support('html5', array('search-form', 'comment-form', 'comment-list', 'gallery', 'caption', 'style', 'script'));

        add_theme_support('woocommerce');
        add_theme_support('wc-product-gallery-zoom');
        add_theme_support('wc-product-gallery-lightbox');
        add_theme_support('wc-product-gallery-slider');

        register_nav_menus(array(
            'primary' => __('Primary Menu', 'wally-grow-child'),
        ));
    }
}
add_action('after_setup_theme', 'wally_grow_child_setup');

if (!function_exists('wally_grow_child_enqueue_assets')) {
    function wally_grow_child_enqueue_assets() {
        wp_enqueue_style(
            'wally-grow-fonts',
            'https://fonts.googleapis.com/css2?family=Hanken+Grotesk:wght@400;500;600;700&family=Manrope:wght@400;600;700&display=swap',
            array(),
            null
        );

        wp_enqueue_style(
            'blocksy-parent-style',
            get_template_directory_uri() . '/style.css',
            array(),
            wp_get_theme('blocksy')->get('Version')
        );

        wp_enqueue_style(
            'wally-grow-child-style',
            get_stylesheet_uri(),
            array('blocksy-parent-style'),
            WALLY_GROW_CHILD_VERSION
        );

        wp_enqueue_style(
            'wally-grow-child-components',
            get_stylesheet_directory_uri() . '/assets/css/child.css',
            array('wally-grow-child-style', 'ct-main-styles'),
            WALLY_GROW_CHILD_VERSION
        );

        wp_enqueue_script(
            'wally-grow-child-script',
            get_stylesheet_directory_uri() . '/assets/js/child.js',
            array(),
            WALLY_GROW_CHILD_VERSION,
            true
        );
    }
}
add_action('wp_enqueue_scripts', 'wally_grow_child_enqueue_assets');

/**
 * Blocksy's Customizer currently requests Open Sans. The brand fonts above
 * replace it globally, so the unused request can be removed safely.
 */
add_action('wp_enqueue_scripts', function () {
    wp_dequeue_style('blocksy-fonts-font-source-google');
}, 100);

/**
 * Disable Blocksy Companion's trending-posts strip.
 *
 * The extension was rendering the default "Hello world!" post immediately
 * before the global footer. Pointing its output at an unused hook prevents
 * that entire section from being added to public pages.
 */
add_filter('theme_mod_trending_block_location', function () {
    return 'wally_grow:disabled_trending_block';
});

add_action('wp', function () {
    remove_all_actions('blocksy:template:after', 50);
}, PHP_INT_MAX);

require_once get_stylesheet_directory() . '/inc/setup.php';
require_once get_stylesheet_directory() . '/inc/woocommerce.php';
require_once get_stylesheet_directory() . '/inc/footer.php';
